version: “3”
services:
  app_name:
    build: .
    volumes:
       - .:/app
    environment:
       - POSTGRES_HOST=hh-pgsql-public.ebi.ac.uk
       - POSTGRES_USER=reader
       - POSTGRES_PASSWORD=NWDMCE5xdipIjRrp
       - POSTGRES_DB=pfmegrnargs
       - POSTGRES_PORT=5432
    ports:
       - "8501:8501"
    depends_on:
       - db_name
    command: python -m streamlit run app/streamlit_app.py   
  db_name:
    image: postgres:latest
    environment:
       - POSTGRES_HOST=hh-pgsql-public.ebi.ac.uk
       - POSTGRES_USER=reader
       - POSTGRES_PASSWORD=NWDMCE5xdipIjRrp
       - POSTGRES_DB=pfmegrnargs
       - POSTGRES_PORT=5432
    ports:
       - "5432"
    volumes:
       - ./data:/var/lib/postgresql/data
